Allow peptide table names for intensity datasets

diff --git a/scripts/lint b/scripts/lint
--- a/scripts/lint
+++ b/scripts/lint
@@ -2,6 +2,11 @@
 
 set -e
 
+if [ -z "${CONDA_ENV_NAME}" ]; then
+    echo "Error: CONDA_ENV_NAME environment variable is not set"
+    exit 1
+fi
+
 if ! (( $(conda env list | grep "^${CONDA_ENV_NAME}[[:space:]]*" >/dev/null 2>&1)) ); then
   echo "creating conda environment ${CONDA_ENV_NAME}"
   conda create -y --name $CONDA_ENV_NAME python=3.11
